use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# InvestingWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :investing, InvestingWeb.Endpoint,
  load_from_system_env: true,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :investing, Investing.Mailer,
  adapter: Bamboo.SendgridAdapter,
  api_key: "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"


config :investing, InvestingWeb.Endpoint, server: true

# Add GitHub to your Überauth configuration
config :ueberauth, Ueberauth,
  # providers are who can user authenticate with for our application
  providers: [
    github: { Ueberauth.Strategy.Github, []}
  ]


# Update your provider configuration
config :ueberauth, Ueberauth.Strategy.Github.OAuth,
  client_id: "94ce5989e1edc92d15d6",
  client_secret: "d14b8d8c4dcec7aa00b5de08aa32bfcd08e5faf3"

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
